### ISSUE TITLE
jnigen can't work on Android Studio 4.0

### ISSUE THREAD

**Issue by qtfreet00** [smartsheet-mobile/smjni#2]
error:Unable to load class 'kotlin.reflect.KDeclarationContainer'.

**Comment by gershnik** [comment]
@qtfreet00 Is it on all default settings? It worked fine for me in a quick test but my Android Studio and test project are an upgrade from 3.x

**Comment by qtfreet00** [comment]
@gershnik yes default setting in wiki

**Comment by gershnik** [comment]
@qtfreet00 I tried it in a few different ways and it worked fine, so not sure what it is. Two ideas:
1. Do you have Kotlin plugin installed in Android Studio? (Preferences->Languages & Frameworks -> Kotlin). Perhaps its absence is what causes that Kotlin class to not be available?
2. If the above isn't the issue, can you create a small sample project that reproduces the problem, zip it and attach here? Perhaps something in your project is different from how I tried it.

**Comment by gershnik** [comment]
Closing as non-repro
